Repository scikit-learn-contrib/fastcan, pull requests merged in 2025-07, with the labels that each got.

#121 FEAT add auto-regressive model in NARX
  fastcan/narx.py
  tests/test_narx.py
Labels: enhancement

#124 DOC add plantuml C4 diagram
  .github/workflows/emscripten.yml
  .github/workflows/static.yml
  .github/workflows/test.yml
  .github/workflows/wheel.yml
  .readthedocs.yml
  README.rst
  doc/conf.py
  doc/diagram.puml
  doc/index.rst
  pixi.lock
  pyproject.toml
  scripts/rtd_pre_install.sh
  tests/test_narx.py
Labels: documentation

#127 DOC change order of logos
  doc/index.rst
  pixi.lock
  pyproject.toml
Labels: documentation, good first issue
